update archinstall box

diff --git a/VMs/Packer/mkbox b/VMs/Packer/mkbox
--- a/VMs/Packer/mkbox
+++ b/VMs/Packer/mkbox
@@ -1,5 +1,5 @@
 #!/bin/bash
-# execute in .pkr.hcl directory
+# basic script to build a box from a Packer template and add it to Vagrant
 
 PACKER_FILE_PATH="${1:-}"
 BOX_NAME="${2:-packer$(date +%Y.%m.%d)}"
@@ -9,6 +9,11 @@ touch /tmp/time_marker_mkbox
 
 if [[ -z "${PACKER_FILE_PATH}" ]]; then
   echo "Usage: $0 <packer_file_path> [box_name]"
+  exit 1
+fi
+
+if [[ "$(dirname "${PACKER_FILE_PATH}")" != "." ]]; then
+  echo "Error: Run this command in the directory where the Packer file is located."
   exit 1
 fi
 
@@ -25,9 +30,9 @@ else
 fi
 
 packer fmt "${PACKER_FILE_PATH}"
-packer build "${PACKER_FILE_PATH}"
-
-find "${DIR_TO_CHECK}" -maxdepth 1 -type f -newer /tmp/time_marker_mkbox | while read -r new_file; do
-  vagrant box add --name "${BOX_NAME}" "${new_file}"
-done
-rm -f /tmp/time_marker_mkbox
+if packer build "${PACKER_FILE_PATH}"; then
+  find "${DIR_TO_CHECK}" -maxdepth 1 -type f -newer /tmp/time_marker_mkbox | while read -r new_file; do
+    vagrant box add --name "${BOX_NAME}" "${new_file}"
+  done
+  rm -f /tmp/time_marker_mkbox
+fi
